name: Build, Package, and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]  
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # dependencies cache

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka zstandard flake8 mypy types-aiofiles

    - name: Lint with flake8 and mypy
      run: |
        echo "Running flake8..."
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=F824
        echo "Running mypy..."
        mypy src/ --explicit-package-bases --ignore-missing-imports 

    - name: Build exe with Nuitka
      run: |
        python -m nuitka --standalone --onefile --windows-disable-console`
          --plugin-enable=tk-inter `
          --windows-icon-from-ico=assets/SaveLC.ico `
          --output-filename=SaveLiveCaptions.exe `
          --output-dir=dist `
          src/main.py  

    - name: Upload to Artifacts (for quick testing)
      uses: actions/upload-artifact@v4
      with:
        name: savelivecaptions-exe
        path: dist/SaveLiveCaptions.exe
        retention-days: 7  

    - name: Create Release and Upload exe (only on tags)
      if: startsWith(github.ref, 'refs/tags/')  
      uses: softprops/action-gh-release@v2  
      with:
        files: dist/savelivecaptions.exe
        tag_name: ${{ github.ref_name }}  
        name: Release ${{ github.ref_name }}
        body: |
          ## 新版本发布！
          ## NEW Release
          - 下载 Save Live Captions.exe 双击运行（无需安装 Python）。
          - Download the exe to run the application.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动授权
